### ISSUE TITLE
Importing in a project with Vite + React results in __vite_ssr_import_5__.default is not a constructor 

### ISSUE THREAD

**Issue by th0th** [NTag/dotted-map#13]
Hey, first, thanks for making this available 💐 

I am trying to use this in a Vite React project, but when I import with

```typescript
import DottedMap from "dotted-map";
```
I get this error:

```
__vite_ssr_import_5__.default is not a constructor
```

Any idea what might be the cause?

**Comment by NTag** [comment]
Arf I already saw this error, I think the library isn't greatly bundled…

Can you try to do:
```js
import DottedMapRaw from "dotted-map";

const DottedMap = DottedMapRaw.default;
```

and see if it works better?

**Comment by th0th** [comment]
> Arf I already saw this error, I think the library isn't greatly bundled…
> 
> Can you try to do:
> 
> ```js
> import DottedMapRaw from "dotted-map";
> 
> const DottedMap = DottedMapRaw.default;
> ```
> 
> and see if it works better?

Thanks for the quick reply. But unfortunately, it doesn't work. It results in this typescript error:

```
TS2339: Property default does not exist on type typeof DottedMap
```

**Comment by NTag** [comment]
Hum actually I just tested a blank JS Vite + React project, and I am able to use as expected the library. You can see the "demo project" here: https://github.com/NTag/demo-dotted-map-vite/blob/main/src/App.jsx

To help you further more I'd need more code, or ideally a repo example.

**Comment by th0th** [comment]
The repo I am working on is way too complex to simplify and share 😅 I went for a workaround and directly copied the functions I needed from the file and put it in a file in the project, and imported from there. So, I think we can close this issue. And once again, thank you for making this, and for your time on this issue, too! 💐

**Comment by NTag** [comment]
Alright, I understand, glad you have something working in the end 👌 .
