### ISSUE TITLE
What is the license of this code?

### ISSUE THREAD

**Issue by ziolko** [NTag/dotted-map#2]
Thanks @NTag for this nice library!

What is the license of this code? Could you add a `LICENSE.txt` file?

Mateusz

**Comment by NTag** [comment]
Thank you!

MIT licence, I just added a `LICENSE` file to the repository.

**Comment by ziolko** [comment]
Thanks! FYI I used parts of the code at https://github.com/ziolko/roombelt-activity-map.

**Comment by NTag** [comment]
Nice! Happy to see this project used ☺️
