### ISSUE TITLE
Country extraction

### ISSUE THREAD

**Issue by pjotterplotter** [NTag/dotted-map#6]
Thanks for the nice library!
One problem i stumbled upon: I tried to extract a specific country svg, but when i do, it throws an error:

`c:\dev\map>node map.js
c:\dev\map\node_modules\dotted-map\index.js:1
(function (exports, require, module, __filename, __dirname) { !function(e,t){"object"==typeof exports&&"object"==typeof module?module.exports=t(require("proj4"),require("@turf/boolean-point-in-polygon")):"function"==typeof define&&define.amd?define(["proj4","@turf/boolean-point-in-polygon"],t):"object"==typeof exports?exports["dotted-map"]=t(require("proj4"),require("@turf/boolean-point-in-polygon")):e["dotted-map"]=t(e.proj4,e["@turf/boolean-point-in-polygon"])}(this,(function(e,t){return(()=>{"use strict";var o={573:(e,t,o)=>{o.r(t),o.d(t,{default:()=>c,getMapJSON:()=>u});var r=o(25),a=o.n(r),n=o(620),i=o.n(n);const p=JSON.parse('{"type":"FeatureCollection","features":[{"type":"Feature","id":"AFG","properties":{"name":"Afghanistan"},"geometry":{"type":"Polygon","coordinates":[[[61.210817,35.650072],[62.230651,35.270664],[62.984662,35.404041],[63.193538,35.857166],[63.982896,36.007957],[64.546479,36.312073],[64.746105,37.111818],[65.588948,37.305217],[65.745631

TypeError: a.flat is not a function
    at m (c:\dev\map\node_modules\dotted-map\index.js:1:257925)
    at m (c:\dev\map\node_modules\dotted-map\index.js:1:257823)
    at Array.map (<anonymous>)
    at m (c:\dev\map\node_modules\dotted-map\index.js:1:257617)
    at l (c:\dev\map\node_modules\dotted-map\index.js:1:258331)
    at new c (c:\dev\map\node_modules\dotted-map\index.js:1:259269)
    at Object.<anonymous> (c:\dev\map\map.js:26:13)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)`

This is the code i used:

`const fs = require('fs');
const DottedMap = require('dotted-map').default;

const map = new DottedMap(
	{ 
		height: 100, 
		grid: 'vertical',//'diagonal',
		countries: ['FRA'],
  		avoidOuterPins: false
	});

const svgMap = map.getSVG({
  radius: 0.22,
  color: '#000',
  shape: 'circle',
});

console.log(svgMap);`

Did i miss something?

**Comment by pjotterplotter** [comment]
Never mind, tried running it online here:
https://runkit.com/embed/leng1ls69gse

Which works, must be a node version issue :S

**Comment by NTag** [comment]
Yes, I think you're using a too old version of node, `Array.flat` has been added in recent versions.
