### ISSUE TITLE
Custom popup on markers

### ISSUE THREAD

**Issue by sincerely91** [NTag/dotted-map#8]
Is it possible to add custom popup on markers of the hexagon map?
I am just gonna add a popup on markers on the hexagon map.

**Comment by Mrkk108** [comment]
Did you find it?

**Comment by sincerely91** [comment]
Yes, I did. 
You can check here. 
https://github.com/elastos-trinity/HiveHub.WebApp/tree/master/src/components/Dashboard/Explore/WorldMap
